const fs = require("fs");
const Hapi = require("@hapi/hapi");

const server = Hapi.server({
  host: "localhost",
  port: Number(process.argv[2] || 6969),
});

server.route({
  method: "GET",
  path: "/",
  config: {
    cors: {
      origin: ["*"],
      additionalHeaders: ["cache-control", "x-requested-with"],
    },
  },
  handler: function (request, reply) {
    return [
      {
        NOSBK: "00026",
        NAMA: "FENI AGUSTINA",
        TGSBK: "13/02/2020",
        UP: 8000000,
        KETER1: "SATU GELANG RANTE PL",
        KETER2: "BRT50.59GRAM===",
        KETER3: "",
        SEWA: "",
        TGLLUNAS: "",
        JANGKA: "",
        GOL: "",
        JAN: "",
        PEB: 0,
        MAR: 666667,
        APR: 666667,
        MEI: "",
        JUN: "",
        JUL: "",
        AGS: "",
        SEP: "",
        OKT: "",
        NOP: "",
        DES: "",
        SOAWAL: "",
        SOAKHIR: 1333334,
        VOLOAWAL: "",
        VOLAKHIR: "",
        SM01: "",
        SM02: 0,
        SM03: 88000,
        SM04: 88000,
        SM05: "",
        SM06: "",
        SM07: "",
        SM08: "",
        SM09: "",
        SM10: "",
        SM11: "",
        SM12: "",
        SMAWAL: "",
        SMAKHIR: 176000,
      },
      {
        NOSBK: "00029",
        NAMA: "SAODJA",
        TGSBK: "19/02/2020",
        UP: 2456000,
        KETER1: "SATU GELANG BIJI LAD",
        KETER2: "BERAT5.95GRAM===",
        KETER3: "",
        SEWA: "",
        TGLLUNAS: "",
        JANGKA: "",
        GOL: "",
        JAN: "",
        PEB: "",
        MAR: 204667,
        APR: 204667,
        MEI: "",
        JUN: "",
        JUL: "",
        AGS: "",
        SEP: "",
        OKT: "",
        NOP: "",
        DES: "",
        SOAWAL: "",
        SOAKHIR: 409334,
        VOLOAWAL: "",
        VOLAKHIR: "",
        SM01: "",
        SM02: "",
        SM03: 27016,
        SM04: 27016,
        SM05: "",
        SM06: "",
        SM07: "",
        SM08: "",
        SM09: "",
        SM10: "",
        SM11: "",
        SM12: "",
        SMAWAL: "",
        SMAKHIR: 54032,
      },
      {
        NOSBK: "00030",
        NAMA: "FARIDA DAMAYANTI",
        TGSBK: "20/02/2020",
        UP: 928000,
        KETER1: "SATU CINCIN MATA GEL",
        KETER2: "T BERAT2.06/2GRAM===",
        KETER3: "",
        SEWA: "",
        TGLLUNAS: "",
        JANGKA: "",
        GOL: "",
        JAN: "",
        PEB: "",
        MAR: 154667,
        APR: 154667,
        MEI: "",
        JUN: "",
        JUL: "",
        AGS: "",
        SEP: "",
        OKT: "",
        NOP: "",
        DES: "",
        SOAWAL: "",
        SOAKHIR: 309334,
        VOLOAWAL: "",
        VOLAKHIR: "",
        SM01: "",
        SM02: "",
        SM03: 10208,
        SM04: 10208,
        SM05: "",
        SM06: "",
        SM07: "",
        SM08: "",
        SM09: "",
        SM10: "",
        SM11: "",
        SM12: "",
        SMAWAL: "",
        SMAKHIR: 20416,
      },
      {
        NOSBK: "00126",
        NAMA: "ANITA BONITA",
        TGSBK: "11/05/2020",
        UP: 3632000,
        KETER1: "SATU KALUNG RANTAI D",
        KETER2: "BERAT7.91GRAM===",
        KETER3: "",
        SEWA: "",
        TGLLUNAS: "",
        JANGKA: "",
        GOL: "",
        JAN: "",
        PEB: "",
        MAR: "",
        APR: "",
        MEI: "",
        JUN: "",
        JUL: "",
        AGS: "",
        SEP: "",
        OKT: "",
        NOP: "",
        DES: "",
        SOAWAL: "",
        SOAKHIR: "",
        VOLOAWAL: "",
        VOLAKHIR: "",
        SM01: "",
        SM02: "",
        SM03: "",
        SM04: "",
        SM05: "",
        SM06: "",
        SM07: "",
        SM08: "",
        SM09: "",
        SM10: "",
        SM11: "",
        SM12: "",
        SMAWAL: "",
        SMAKHIR: "",
      },
      {
        NOSBK: "00127",
        NAMA: "ANITA BONITA",
        TGSBK: "11/05/2020",
        UP: 3443000,
        KETER1: "LIMA KEPING LM HA DT",
        KETER2: "ERAT5GRAM===",
        KETER3: "",
        SEWA: "",
        TGLLUNAS: "",
        JANGKA: "",
        GOL: "",
        JAN: "",
        PEB: "",
        MAR: "",
        APR: "",
        MEI: "",
        JUN: "",
        JUL: "",
        AGS: "",
        SEP: "",
        OKT: "",
        NOP: "",
        DES: "",
        SOAWAL: "",
        SOAKHIR: "",
        VOLOAWAL: "",
        VOLAKHIR: "",
        SM01: "",
        SM02: "",
        SM03: "",
        SM04: "",
        SM05: "",
        SM06: "",
        SM07: "",
        SM08: "",
        SM09: "",
        SM10: "",
        SM11: "",
        SM12: "",
        SMAWAL: "",
        SMAKHIR: "",
      },
    ];
  },
});

const init = async () => {
  await server.start();
  console.log(`Server running at: ${server.info.uri}`);
};

init();
